### ISSUE TITLE
Printing glossaries

### ISSUE THREAD

**Issue by Smokrow** [ProdriveTechnologies/bazel-latex#44]
Hey there,

I am currently trying to switch my latex-thesis to Bazel. In order to add the glossaries with the \printglossary command, you have to invoke the makeglossaries command after compiling your tex files and recompile everything again afterward.  
Any idea how to incorporate this with bazel-latex or is there a trick? 

The compilation process runs fine when I use it the same way as shown in the test, but the glossary does not show up.

Not quite sure if this belongs here. Feel free to close this issue in case it does not :)

Greets! Thanks for the awesome work

**Comment by patbro** [comment]
Hi there! More than happy to help you out with this.

There are [two ](https://github.com/ProdriveTechnologies/bazel-latex/blob/master/packages/glossaries_test.tex) [glossary ](https://github.com/ProdriveTechnologies/bazel-latex/blob/master/packages/glossaries-extra_test.tex )tests available. Both tests invoke `\makeglossaries`. Is your use case similar to those tests? If not, could you perhaps explain what's different and share an example?

**Comment by Smokrow** [comment]
Yes I just tried running the example as well. Turns out it compiles fine but in the PDF the glossary does not show up.

**Comment by patbro** [comment]
Ah, I see. You're totally right. Unfortunately, I can't be sure the glossaries did show up in the past. Since glossaries seem not to be supported by LaTeX run at the time of writing. Though, there are two open issues, requesting this functionality. 

Furthermore, I attempted to use `\usepackage[nomain]{glossaries-extra}` with shell escape enabled. But this didn't change a thing.

We might be able to get it to work without this functionality incorporated in LaTeX run. Though then it might be better to just directly add this functionality to LaTeX run. I will take a closer look at this in the upcoming weeks. Please send let me know if you have any additional thoughts on this. Cheers!

**Comment by Smokrow** [comment]
I had a similar problem when using latexmk. I solved that by adding a subroutine to the .latexmkrc file in the folder which basically reran the compilation process. https://tex.stackexchange.com/questions/1226/how-to-make-latexmk-use-makeglossaries

If you have any ideas where we could get started I would be glad to help out :).

Greets

**Comment by patbro** [comment]
That might be a feasible solution as well. I also noticed someone already made a primitive implementation of a makeglossaries task in LaTeX run: https://github.com/karlek/latexrun/tree/makeglossaries-task 

You can get in touch with me via email at github@patb.ro. Let's take it from there.
