### ISSUE TITLE
xelatex

### ISSUE THREAD

**Issue by wix-andriusb** [ProdriveTechnologies/bazel-latex#49]
Is it possible to use xelatex? I see lualatex, but it seems to be really slow for me.

**Comment by patbro** [comment]
The example report needs a total of 18 seconds to build on my machine. So, it's not very fast, but I'm not sure whether XeLaTeX could do it in less time. XeLaTeX mainly has some advantages regarding the usage of external fonts, rather than speed improvements. 

I do believe it's a good feature to consider adding support for. I do foresee challenges supporting both LuaLaTex and XeLaTeX.  Then it might be wise to drop support for one of those.

**Comment by wix-andriusb** [comment]
What do you think will make it difficult yo support both?

**Comment by patbro** [comment]
Both solutions attempt to achieve the same thing, which boils down to converting your LaTeX document to a PDF document. Furthermore, some documents can only be built with XeLaTeX and not with LuaLaTeX. Not speaking of some packages which won't work with LuaLaTex [1](https://tex.stackexchange.com/a/111625). 

We could definitely make it work, but it might only just add unnecessary complexity to bazel-latex. Please let me if I'm missing something obvious here.
